# Basic
title: 游客
subtitle: 仗剑走天涯
welcome_message: 这个人很懒，什么都没有。
description: 在下王毅安(@John)，请多指教。
creator: <a href="http://oneyian.cn">@John</a>

url: "http://oneyian.cn"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: 简历, description: 我的简历, url: 'http://message.oneyian.cn'}
    - {title: 关于, description: 了解更多关于我, url: 'http://about.oneyian.cn'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: John
    # duoshuo:
# Social
social:
    weibo: 3927928511
    github: oneyian
    twitter: John_YiAn
    gplus: 107600099440304236442
    mail: wangyian1997@foxmail.com

# Google Analytics
ga:
    id: UA-25719337-1
    host: oneyian.cn