# Basic
title: OneYiAn`
subtitle: 仗剑走天涯
welcome_message: 2017年开发过iOS平台的—> 新闻、通讯、电商类APP，您可以在 <a href="https://github.com/oneyian">GitHub</a> 查看我的开源项目；2018年计划：Swift与Mac开发，网站与后台
description: 在下王毅安(@John)，现居南昌的正经开发者，爱好摸爬滚打(@混吃等死)；目前正在打磨属于自己的那把 “剑” ，还请多多指教。
creator: <a href="https://oneyian.cn">@John</a>

url: "https://oneyian.cn"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: 简历, description: 我的简历, url: 'ReadMe'}
    - {title: 关于, description: 了解我的世界, url: 'About'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: oneyian
    # duoshuo:
# Social
social:
    weibo: oneyian
    github: oneyian
    twitter: oneyian_
    gplus: 107600099440304236442
    mail: wya@oneyian.cn

# Google Analytics
ga:
    id: UA-111544047-1
    host: oneyian.cn