# Basic
title: Oneyian`
subtitle: “每生产一个BUG，就有一只程序猿会被祭天。”
welcome_message: 熟读《iOS软件—五年开发，三年编译》此书，正在苦读《Swift开发》以及其他小黄书；您可以在 <a href="https://github.com/oneyian">GitHub</a> 查看我的开源项目；
description: 在下王毅安(@John)，混吃等死的正经开发者；目前正在打磨属于自己的那把 “剑” ，请多指教。
creator: <a href="https://oneyian.com">@John</a>

url: "https://oneyian.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: 简历, description: 我的简历, url: 'https://oneyian.com/ReadMe'}
    - {title: 关于, description: 了解我的世界, url: 'https://oneyian.com/About'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: oneyian
    # duoshuo:
# Social
social:
    weibo: oneyian
    github: oneyian
    twitter: oneyian_
    gplus: 107600099440304236442
    mail: wya@oneyian.com

# Google Analytics
ga:
    id: UA-111544047-1
    host: oneyian.com
