# Basic
title: 游客
subtitle: 仗剑走天涯
welcome_message: 念念不忘，必有回响
description: 在下王毅安(@John)，请多指教。
creator: <a href="https://oneyian.cn">@John</a>

url: "https://oneyian.cn"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: 简历, description: 我的简历, url: 'https://self.oneyian.cn'}
    - {title: 关于, description: 了解更多关于我, url: 'https://me.oneyian.cn'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: oneyian
    # duoshuo:
# Social
social:
    weibo: 3927928511
    github: oneyian
    twitter: oneyian_
    gplus: 107600099440304236442
    mail: wangyian1997@foxmail.com

# Google Analytics
ga:
    id: UA-111544047-1
    host: oneyian.cn